export const PaymentData = [
  {
    id: "#EDU-1001",
    date: "2025-07-15",
    time: "10:00 AM",
    user: "Alice Johnson",
    type: "Booking Payment",
    amount: 1200,
    method: "Stripe",
    status: "Paid",
  },
  {
    id: "#EDU-1002",
    date: "2025-07-16",
    time: "2:30 PM",
    user: "Brian Smith",
    type: "Booking Payment",
    amount: 300,
    method: "Bank",
    status: "Paid",
  },
  {
    id: "#EDU-1003",
    date: "2025-07-17",
    time: "11:45 AM",
    user: "Catherine Lee",
    type: "Booking Payment",
    amount: 50,
    method: "UPI",
    status: "In Process",
  },
  {
    id: "#EDU-1004",
    date: "2025-07-18",
    time: "4:15 PM",
    user: "David Wilson",
    type: "Booking Payment",
    amount: 1500,
    method: "Stripe",
    status: "Paid",
  },
  {
    id: "#EDU-1005",
    date: "2025-07-19",
    time: "9:30 AM",
    user: "Emily Brown",
    type: "Booking Payment",
    amount: 1200,
    method: "Bank",
    status: "Failed",
  },
  {
    id: "#EDU-1006",
    date: "2025-07-20",
    time: "1:30 PM",
    user: "Frank Harris",
    type: "Booking Payment",
    amount: 300,
    method: "Stripe",
    status: "Paid",
  },
  {
    id: "#EDU-1007",
    date: "2025-07-21",
    time: "12:00 PM",
    user: "Grace Thompson",
    type: "Booking Payment",
    amount: 75,
    method: "Stripe",
    status: "In Process",
  },
  {
    id: "#EDU-1008",
    date: "2025-07-22",
    time: "3:00 PM",
    user: "Henry Miller",
    type: "Booking Payment",
    amount: 1200,
    method: "UPI",
    status: "Paid",
  },
  {
    id: "#EDU-1009",
    date: "2025-07-23",
    time: "9:15 AM",
    user: "Isabella Clark",
    type: "Booking Payment",
    amount: 1500,
    method: "Stripe",
    status: "In Process",
  },
  {
    id: "#EDU-1010",
    date: "2025-07-24",
    time: "8:30 AM",
    user: "Jack Davis",
    type: "Booking Payment",
    amount: 300,
    method: "Bank",
    status: "Paid",
  },
];
