export const LocUsersData = [
  {
    id: 1,
    name: "Alice Green",
    email: "alice.green@example.com",
    profile: "https://randomuser.me/api/portraits/women/65.jpg",
    loyaltyPoints: 1245,
    badgesEarned: 3,
    lifetimeEarning: 620,
    lastActivity: "2024-04-20",
  },
  {
    id: 2,
    name: "Brian Carter",
    email: "brian.carter@example.com",
    profile: "https://randomuser.me/api/portraits/men/32.jpg",
    loyaltyPoints: 978,
    badgesEarned: 1,
    lifetimeEarning: 310,
    lastActivity: "2024-04-21",
  },
  {
    id: 3,
    name: "Chloe Martinez",
    email: "chloe.martinez@example.com",
    profile: "https://randomuser.me/api/portraits/women/12.jpg",
    loyaltyPoints: 1502,
    badgesEarned: 4,
    lifetimeEarning: 845,
    lastActivity: "2024-04-22",
  },
  {
    id: 4,
    name: "Daniel Roberts",
    email: "daniel.roberts@example.com",
    profile: "https://randomuser.me/api/portraits/men/76.jpg",
    loyaltyPoints: 1120,
    badgesEarned: 2,
    lifetimeEarning: 420,
    lastActivity: "2024-04-23",
  },
  {
    id: 5,
    name: "Eva Lopez",
    email: "eva.lopez@example.com",
    profile: "https://randomuser.me/api/portraits/women/29.jpg",
    loyaltyPoints: 1340,
    badgesEarned: 5,
    lifetimeEarning: 990,
    lastActivity: "2024-04-24",
  },
  {
    id: 6,
    name: "Frank Miller",
    email: "frank.miller@example.com",
    profile: "https://randomuser.me/api/portraits/men/45.jpg",
    loyaltyPoints: 890,
    badgesEarned: 1,
    lifetimeEarning: 250,
    lastActivity: "2024-04-25",
  },
];
