export const RefundData = [
  {
    _id: "r1",
    transactionId: "#BK-1092",
    date: "2025-07-15",
    time: "2:00 PM",
    client: "Paul Martin",
    type: "Booking Refund",
    amount: 555,
    method: "Stripe",
    status: "Refunded",
  },
  {
    _id: "r8",
    transactionId: "#BK-1098",
    date: "2025-07-22",
    time: "2:45 PM",
    client: "Liam Wilson",
    type: "Booking Refund",
    amount: 650,
    method: "Stripe",
    status: "Refunded",
  },
  {
    _id: "r9",
    transactionId: "#ORD-2019",
    date: "2025-07-23",
    time: "3:00 PM",
    client: "Sophia White",
    type: "Product Refund",
    amount: 400,
    method: "Stripe",
    status: "Refunded",
  },
  {
    _id: "r10",
    transactionId: "#BK-1100",
    date: "2025-07-24",
    time: "9:15 AM",
    client: "Ethan Harris",
    type: "Booking Refund",
    amount: 900,
    method: "Stripe",
    status: "Refunded",
  },
  {
    _id: "r11",
    transactionId: "#BK-1101",
    date: "2025-07-25",
    time: "8:30 AM",
    client: "Isabella Clark",
    type: "Product Refund",
    amount: 350,
    method: "Stripe",
    status: "Refunded",
  },
  {
    _id: "r14",
    transactionId: "#BK-1104",
    date: "2025-07-28",
    time: "1:00 PM",
    client: "Alexander Walker",
    type: "Booking Refund",
    amount: 950,
    method: "Stripe",
    status: "Refunded",
  },
];
