export const productdata = [
  {
    id: 1,
    product:{
            name:"Aloe Locking Gel",
            category:"Skin Care",
            profile: `https://picsum.photos/512?random=${Math.floor(Math.random()*100)}`,
        },
    order_id: "#4194i-012i4-04i10",
    date_time: "2025-08-05T10:00:00Z",
    amount: "160",
    status: "active",
    actions: [
      { id: 1, action: "View Order", url: "/users/1" },
      { id: 2, action: "Mark as Delivered", url: "/users/1/complete" },
      { id: 3, action: "Flag Order", url: "/users/1/flag" },
      { id: 4, action: "Download Invoice", url: "/users/1/download" },
      { id: 5, action: "Cancel Order", url: "/users/1/delete" },
    ],
  },
  {
    id: 2,
    product:{
            name:"Aloe Locking Gel",
            category:"Skin Care",
            profile: `https://picsum.photos/512?random=${Math.floor(Math.random()*100)}`,
        },
    order_id: "#4194i-012i4-04i10",
    date_time: "2025-08-05T13:30:00Z",
    stylist: "Ava",
    amount: "140",
    status: "pending",
    actions: [
      { id: 1, action: "View Order", url: "/users/1" },
      { id: 2, action: "Mark as Delivered", url: "/users/1/complete" },
      { id: 3, action: "Flag Order", url: "/users/1/flag" },
      { id: 4, action: "Download Invoice", url: "/users/1/download" },
      { id: 5, action: "Cancel Order", url: "/users/1/delete" },
    ],
  },
  {
    id: 3,
    product:{
            name:"Aloe Locking Gel",
            category:"Skin Care",
            profile: `https://picsum.photos/512?random=${Math.floor(Math.random()*100)}`,
        },
    order_id: "#4194i-012i4-04i10",
    date_time: "2025-08-06T09:15:00Z",
    stylist: "Jay",
    amount: "120",
    status: "completed",
     actions: [
      { id: 1, action: "View Order", url: "/users/1" },
      { id: 2, action: "Mark as Delivered", url: "/users/1/complete" },
      { id: 3, action: "Flag Order", url: "/users/1/flag" },
      { id: 4, action: "Download Invoice", url: "/users/1/download" },
      { id: 5, action: "Cancel Order", url: "/users/1/delete" },
    ],
  },
  {
    id: 4,
    product:{
            name:"Aloe Locking Gel",
            category:"Skin Care",
            profile: `https://picsum.photos/512?random=${Math.floor(Math.random()*100)}`,
        },
    order_id: "#4194i-012i4-04i10",
    date_time: "2025-08-06T15:00:00Z",
    stylist: "Prab",
    amount: "180",
    status: "cancelled",
     actions: [
      { id: 1, action: "View Order", url: "/users/1" },
      { id: 2, action: "Mark as Delivered", url: "/users/1/complete" },
      { id: 3, action: "Flag Order", url: "/users/1/flag" },
      { id: 4, action: "Download Invoice", url: "/users/1/download" },
      { id: 5, action: "Cancel Order", url: "/users/1/delete" },
    ],
  },
  {
    id: 5,
    product:{
            name:"Aloe Locking Gel",
            category:"Skin Care",
            profile: `https://picsum.photos/512?random=${Math.floor(Math.random()*100)}`,
        },
    order_id: "#4194i-012i4-04i10",
    date_time: "2025-08-07T11:45:00Z",
    stylist: "Lena",
    amount: "70",
    status: "active",
     actions: [
      { id: 1, action: "View Order", url: "/users/1" },
      { id: 2, action: "Mark as Delivered", url: "/users/1/complete" },
      { id: 3, action: "Flag Order", url: "/users/1/flag" },
      { id: 4, action: "Download Invoice", url: "/users/1/download" },
      { id: 5, action: "Cancel Order", url: "/users/1/delete" },
    ],
  },
];
